--- 
after_success: 
  - "coverage combine"
  - codecov
  - coveralls
branches: 
  only: 
    - master
ignore_changes: 
  - README.md
  - .gitignore
language: python
python: 
  - "3.6"
script: 
  - "coverage run test_case.py"
sudo: false
